fix

diff --git a/lib/pack-util b/lib/pack-util
--- a/lib/pack-util
+++ b/lib/pack-util
@@ -27,24 +27,30 @@ for item in ${CMD[@]}; do
         echo -e "Packet from '$item':\n\t\033[36m"`ls -p $PKGS/$item`"\033[0m\n" && \
         continue
 
-    [[ ! -x $PKGS/$item ]] && \
-        echo -e "\033[31mError: packet '$item' not found!\033[0m" && \
+    if [[ ! -e $PKGS/$item ]]; then
+        echo -e "\033[31m***"
+        echo -e "*** Error: packet '$item' not found! ***"
+        echo -e "***\033[0m"
+
+        [[ ! $INSTALL ]] && continue
         exit 1
+    fi
 
     # init default package variables and methods
     TITLE=""
     DESCRIPTION=""
     PACKAGES=()
     CONFIGS=()
-    pre_install() { echo "pre-install handler"  > /dev/null; }
-    pre_config()  { echo "pre-config handler"   > /dev/null; }
-    install()     { echo "post-install handler" > /dev/null; }
+    pre_install() { echo -e "\033[33m\t- skip\033[0m"; }
+    pre_config()  { echo -e "\033[33m\t- skip\033[0m"; }
+    install()     { echo -e "\033[33m\t- skip\033[0m"; }
     to_install=()
 
     source $PKGS/$item
 
-    echo -e "\033[33m-- Packet '$item' --\033[0m"
-    echo -e "\033[33m   ${TITLE}\033[0m"
+    echo -e "\033[33m$(perl -E 'say "-" x 60')\033[0m"
+    echo -e "\033[33m-- Packet $item - ${TITLE:-...}\033[0m"
+    echo -e "\033[33m$(perl -E 'say "-" x 60')\033[0m"
 
     [[ ${DESCRIPTION} ]] && \
         echo -e "${DESCRIPTION}"
@@ -64,7 +70,8 @@ for item in ${CMD[@]}; do
         echo "" && continue
 
     # exec pre-install handler
-    pre_install || exit 1
+    echo -e "Run pre-install script:" && \
+        pre_install || exit 1
 
     if [[ ${to_install} ]]; then 
         echo -e "Install packages:\n\t\033[36m${to_install[@]}\033[0m"
@@ -72,7 +79,8 @@ for item in ${CMD[@]}; do
     fi
 
     # exec pre-config handler
-    pre_config || exit 1
+    echo -e "Run pre-configure script:" && \
+        pre_config || exit 1
 
     if [[ ${CONFIGS} ]]; then
         echo -e "Copy config files:"
@@ -83,7 +91,8 @@ for item in ${CMD[@]}; do
     fi
 
     # exec post-install handler
-    install || exit 1
+    echo -e "Run post-install script:" && \
+        install || exit 1
 
     echo -e "\033[32m[+] install '$item' is complete\033[0m\n"
 done
